[package]
name = "serf-rpc"
version = "0.3.0"
authors = ["Ben Aubin <ben@benaubin.com>"]
edition = "2018"
repository = "https://github.com/benaubin/serf-rs"
license = "MIT"
description = "A client library for Hashicorp's Serf (https://serf.io)"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.133", features=["std", "derive"] }
rmp-serde = {version = "1.3.0"}
rmpv = { version = "1.3.0", features = ["with-serde"]}
futures = {version="0.3.12"}
rmp = "0.8.10"
serde_bytes = "0.11.5"
log = "0.4"
tokio = { version = "1.2.0", features=["full"] }

[dev-dependencies]
clap = { version = "4.0.0", features = ["derive"]}
env_logger = "0.11.5"
